@baseUrl = http://localhost:3000
@token = 

# USERS
### get all user
GET {{baseUrl}}/api/v1/users
### get user by id
GET {{baseUrl}}/api/v1/users/5
### add user
POST {{baseUrl}}/api/v1/users
Content-Type: application/json

{
    "fullName": "Hoang Chi Trung",
    "email": "trunghoang1128@gmail.com",
    "password": "123456"
}

### AUTHENTICATE
### register
POST {{baseUrl}}/api/v1/auth/register
Content-Type: application/json

{
    "fullName": "HuYGay",
    "email": "test@gmail.com",
    "password": "123456"
}
### login
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
    "email": "trunghoang1128@gmail.com",
    "password": "123456"
}

# PRODUCTS
### get product
GET http://localhost:3000/api/products

### get product by id
GET http://localhost:3000/api/products/2

### add product
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "Intel Core i9-14900K",
  "description": "CPU Intel Core i9 thế hệ 14, socket LGA1700, 24 cores/32 threads",
  "category": "CPU",
  "brand": "Intel",
  "price": 12000000,
  "stock_quantity": 10,
  "tdp": 125,
  "image_url": "/images/cpu-i9.jpg",
  "specifications": "{\"cores\": 24, \"threads\": 32, \"socket\": \"LGA1700\", \"base_clock\": \"3.5GHz\", \"boost_clock\": \"5.8GHz\"}",
  "serial_number_required": false,
  "is_active": true
}

### delete product
DELETE http://localhost:3000/api/products/1

### update product
PUT http://localhost:3000/api/products/2
Content-Type: application/json

{
    "name": "RTX 4090",
    "price": 2500,
    "stock": 5
}